"""
bundle.py - pack the Python agent and the web page into src/bundle.ts.

The Worker cannot read files from your disk. So before deploying we turn
every file the sandbox needs into one TypeScript constant: a dictionary
from path -> file text. The Worker writes those files into the sandbox
the first time a browser session starts.

    python3 bundle.py
"""

import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
PROJECT = HERE.parent.parent

FILES = sorted(
    [str(p.relative_to(PROJECT)) for p in (PROJECT / "agent").glob("*.py")]
    + ["web/index.html", "workspace/README.md"]
)

bundle = {}
for relative in FILES:
    bundle[relative] = (PROJECT / relative).read_text(encoding="utf-8")

out = HERE / "src" / "bundle.ts"
out.write_text(
    "// Generated by bundle.py. Do not edit; run `python3 bundle.py` instead.\n"
    "export const FILES: Record<string, string> = " + json.dumps(bundle, indent=2) + ";\n",
    encoding="utf-8",
)
print(f"wrote {out} with {len(bundle)} files, {sum(len(v) for v in bundle.values())} characters")
